### ISSUE TITLE
Suggestion & Discussion: Ability to use Markdown markup in timeline elements (plugin)

### ISSUE THREAD

**Issue by taqyon** [George-debug/obsidian-timeline#3] opened 2021-07-12 19:06 UTC
# 1. Idea Overview
**The main idea is to allow the user to use Markdown markup in various elements of the plugin.**

Here I am talking about: 
- date
- event title
- event content 

## 2. Entering syntax
Now the `+` symbol is used to add an event to the timeline. I find it inconvenient for several reasons: 
1. It's hard for a person to read
2. This symbol may need to be used. Unlikely, but not impossible.

### 2.1. Here I suggest
Introduce a simple, human-readable syntax, for example: 
- `date:`
- `event-title:`
- `event-content: / event-desc:`

Here I have tried to depict human-readable examples. They are not definitive, perhaps you will find better options. 

## 3. Allow the user to use Markdown markup in various elements
**Why?** So that the user has the ability to style the timeline with Markdown markup. Little room for styling as well as content management. 

### 3.1. Examples of use
```date: ### 26 December <br> 1991```

```event title: # Dissolution of the Soviet Union```

```event-content: The dissolution of the Soviet Union[b] (1988–1991) was the process of internal disintegration within the Soviet Union, which began with growing unrest in its various constituent republics developing into an incessant political and legislative conflict between the republics and the central government, and ended when the leaders of three primal republics (the Russian SFSR, the Ukrainian SSR and the Byelorussian SSR) declared it no longer existed, later accompanied by 11 more republics, resulting in President Mikhail Gorbachev having to resign and what was left of the Soviet parliament formally acknowledging what had already taken place.```

Note the markdown syntax. The user can select the size of the header (H1-H6). Italic or Bold or strikethrough text.

### 3.2. Allowed syntax for timeline elements
To avoid turning the timeline into a visual circus, I propose to introduce some restrictions for elements. 

#### date (Allowed syntax)

- Headers
```
# Heading level 1 
## Heading level 2 
### Heading level 3 
#### Heading level 4 
##### Heading level 5 
###### Heading level 6 
```

- Line breakers aka `<br>` (already work)
- Bold
- Italic
- Bold & Italic
- Strikethrough
- Links

#### event-title (Allowed syntax)
- Headers
```
# Heading level 1 
## Heading level 2 
### Heading level 3 
#### Heading level 4 
##### Heading level 5 
###### Heading level 6 
```

- Line breakers aka `<br>` (already work)
- Bold
- Italic
- Bold & Italic
- Strikethrough
- Links

#### event-description (Allowed syntax)
- Headers
```
# Heading level 1 
## Heading level 2 
### Heading level 3 
#### Heading level 4 
##### Heading level 5 
###### Heading level 6 
```

- Line breakers aka `<br>` (already work)
- Bold
- Italic
- Bold & Italic
- Strikethrough
- Links
- Tables
- Quotes
- Lists
- Tasks
- Numbered Lists

### 3.3. Default state
I also suggest adding a default state. This is for cases where, for example, the user does not use markdown for timeline elements. 

In this case, the timeline is displayed "by default". For example as you have it now. 

---

**PS:** If the idea(s) turn out to be interesting, I can describe more timeline styling features in stages. But do not overload it too much, so that it remains simple and readable.

**Comment by George-debug** [comment] 2021-07-13 10:21
Great suggestions!
The problem is that I don't know how to make settings for the plugin or where I find them or how they look!
I'll close this comment after I have an idea of how the settings API works.

Before the `+` was `-` and before the '-' was a `hard return`. Your Idea of labeling will do great :)
I'll release this version as good, making the `+` default, later adding your style of labeling.

Thanks for the suggestions!

**Comment by taqyon** [comment] 2021-07-13 11:03
> Great suggestions!
> The problem is that I don't know how to make settings for the plugin or where I find them or how they look!
> I'll close this comment after I have an idea of how the settings API works.
> 
> Before the `+` was `-` and before the '-' was a `hard return`. Your Idea of labeling will do great :)
> I'll release this version as good, making the `+` default, later adding your style of labeling.
> 
> Thanks for the suggestions!

Good to hear! Keep me in touch, I'd love to test new versions of the plugin!

**Comment by George-debug** [comment] 2021-09-26 18:00
It's done!

**Closed by George-debug** 2021-09-26 18:00 UTC
